import React, { useRef } from "react";
import ReactToPrint from "react-to-print";

const InvoicePrint = ({ confirmationDetails }) => {
  // Dummy data if not available
  const defaultOrderDetails = {
    customerName: "John Doe",
    cartItems: [
      {
        name: "Medicine A",
        measure: "10mg",
        pricePerStrip: 200,
        stripCount: 2,
        totalPrice: 400,
      },
      {
        name: "Medicine B",
        measure: "20mg",
        pricePerStrip: 150,
        stripCount: 3,
        totalPrice: 450,
      },
    ],
  };

  const defaultCheckoutAmount = {
    subtotal: 850,
    deliveryFee: 50,
    discountedAmount: 100,
    total: 800,
  };

  const {
    orderDetails = defaultOrderDetails,
    invoiceNumber = "INV-123456",
    checkoutAmount = defaultCheckoutAmount,
  } = confirmationDetails || {};

  const invoiceRef = useRef();

  return (
    <div className="container mx-auto p-12 my-8 bg-white shadow-md rounded border">
      <div className="text-center mb-4">
        <ReactToPrint
          trigger={() => (
            <button className="px-4 py-2 bg-blue-500 text-white rounded">
              Print Invoice
            </button>
          )}
          content={() => invoiceRef.current}
        />
      </div>

      <div ref={invoiceRef} className="print-container">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-center mb-2">MediShopBD</h1>
          <p className="text-center text-lg ">
            Address: Road 7, Sector 10, Uttara, Dhaka
          </p>
          <p className="text-center text-lg ">Phone: +880123456789</p>
          <p className="text-center text-lg ">Email: info@company.com</p>
        </div>
        <h2 className="text-2xl font-bold mb-4">Order Receipt</h2>
        <div className="mb-8">
          <p className="text-lg">
            <strong>Invoice Number:</strong> {invoiceNumber}
          </p>
          <div className="text-lg">
            <strong>Date:</strong> {new Date().toLocaleDateString()}{" "}
          </div>
          <div className="text-lg">
            <strong>Time:</strong> {new Date().toLocaleTimeString()}{" "}
          </div>
          <div className="text-lg">
            <strong>Generated By:</strong> MediShopBD System{" "}
          </div>
        </div>

        <div className="flex justify-between mb-6">
          <div>
            <div className="text-xl font-bold underline mb-2">
              Receiver Details:
            </div>
            <div className="text-lg">
              <div>
                <span className="font-semibold">Name:</span>{" "}
                {orderDetails.customerName || "N/A"}
              </div>
              <div>
                <span className="font-semibold">Phone:</span>{" "}
                {orderDetails.phone || "N/A"}
              </div>
              <div>
                <span className="font-semibold">Address:</span>{" "}
                {orderDetails.address || "N/A"}
              </div>
            </div>
          </div>
          <div>
            <div className="text-xl font-bold underline mb-2">
              Sender Details:
            </div>
            <div className="text-lg">
              <div>
                <span className="font-semibold">Name:</span> MediShopBD
              </div>
              <div>
                <span className="font-semibold">Phone:</span> +880123456789
              </div>
              <div>
                <span className="font-semibold">Address:</span> Road 7, Sector
                10, Uttara, Dhaka
              </div>
            </div>
          </div>
        </div>

        <table className="table w-full mb-6 border border-gray-300">
          <thead className="bg-gray-100 text-lg font-semibold">
            <tr>
              <th className="p-2">Item</th>
              <th className="p-2">Price per Strip</th>
              <th className="p-2">Quantity</th>
              <th className="p-2">Total Price</th>
            </tr>
          </thead>
          <tbody className="text-lg">
            {orderDetails.cartItems.map((item, index) => (
              <tr key={index} className="border-b border-gray-200">
                <td className="p-2">{`${item.name} (${item.measure})`}</td>
                <td className="p-2">{`Tk. ${item.pricePerStrip}`}</td>
                <td className="p-2">{item.stripCount}</td>
                <td className="p-2">{`Tk. ${item.totalPrice}`}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <table className="table w-full text-right border border-gray-300">
          <tbody>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Sub Total:</strong>
              </td>
              <td className="py-2">Tk. {checkoutAmount.subtotal}</td>
            </tr>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Delivery Fee:</strong>
              </td>
              <td className="py-2">Tk. {checkoutAmount.deliveryFee}</td>
            </tr>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Discount:</strong>
              </td>
              <td className="py-2">- Tk. {checkoutAmount.discountedAmount}</td>
            </tr>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Total:</strong>
              </td>
              <td className="py-2">Tk. {checkoutAmount.total}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default InvoicePrint;
