'use client'

import Link from "next/link";
import React, { useRef } from "react";
import ReactToPrint from "react-to-print";
import { useDispatch, useSelector } from "react-redux";
import {
  selectOrderDetails,
  selectInvoiceNumber,
  selectOrderCheckoutAmount,
} from "../../redux/features/order/orderSlice";
import { selectUser } from "../../redux/features/user/userSlice";
import { clearCart } from "../../redux/features/cart/cartSlice";

const InvoicePrint = ({ printData }) => {
  const dispatch = useDispatch();
  const { invoiceNumber } = printData;
  const itemDetails = useSelector(selectOrderDetails);

  const checkoutDetails = JSON.parse(localStorage.getItem("checkoutDetails"));
  const medicineCart = JSON.parse(localStorage.getItem("medicine_cart"));
  console.log(checkoutDetails);
  console.log(itemDetails);

  const checkoutAmount = useSelector(selectOrderCheckoutAmount);
  console.log(checkoutDetails);
  const user = useSelector(selectUser);
  console.log(user);

  const invoiceRef = useRef();

  const clearCurrentCart = () => {
    dispatch(clearCart());
  };

  return (
    <div className="container mx-auto p-12 my-8 bg-white shadow-md">
      <div className="flex gap-8 mb-4">
        <ReactToPrint
          trigger={() => (
            <button
              onClick={clearCurrentCart}
              className="px-4 py-2 bg-blue-500 text-white rounded"
            >
              Print Invoice
            </button>
          )}
          content={() => invoiceRef.current}
        />
        <Link
          onClick={clearCurrentCart}
          href="/"
          className="px-4 py-2 bg-blue-500 text-white rounded"
        >
          Return to Homepage
        </Link>
      </div>
      <div className="divider"></div>
      <div ref={invoiceRef} className="print-container p-12">
        <div className="flex justify-between items-end">
          <div className="mb-8">
            <h1 className="text-3xl font-bold">MediShopBD</h1>
            <p>Address: R# 7, S# 10, Uttara, Dhaka</p>
            <p>Phone: +880123456789</p>
            <p>Email: info@medishopbd.com</p>
          </div>
          <div className="mb-8">
            <div>
              <p>
                <strong>Invoice Number:</strong> {invoiceNumber}
              </p>
              <div>
                <strong>Generated By:</strong> MediShopBD System
              </div>
            </div>
            <div>
              <div>
                <strong>Date:</strong> {new Date().toLocaleDateString()}
              </div>
              <div>
                <strong>Time:</strong> {new Date().toLocaleTimeString()}
              </div>
            </div>
          </div>
        </div>
        <h2 className="text-2xl font-bold mb-4">Order Receipt</h2>

        <div className="flex justify-between mb-6">
          <div>
            <div className="text-xl font-bold underline mb-2">
              Receiver Details:
            </div>
            <div className="text-lg">
              <div>
                <span className="font-semibold">Name:</span>{" "}
                {user?.name || "N/A"}
              </div>
              <div>
                <span className="font-semibold">Phone:</span>{" "}
                {user?.phone || "N/A"}
              </div>
              <div>
                <span className="font-semibold">Address:</span>{" "}
                {user?.address || "N/A"}
              </div>
            </div>
          </div>
          <div>
            <div className="text-xl font-bold underline mb-2">
              Sender Details:
            </div>
            <div className="text-lg">
              <div>
                <span className="font-semibold">Name:</span> MediShopBD
              </div>
              <div>
                <span className="font-semibold">Phone:</span> +880123456789
              </div>
              <div>
                <span className="font-semibold">Address:</span> Road 7, Sector
                10, Uttara, Dhaka
              </div>
            </div>
          </div>
        </div>

        <table className="table w-full mb-6 border border-gray-300">
          <thead className="bg-gray-100 text-lg font-semibold">
            <tr>
              <th className="p-2">Item</th>
              <th className="p-2">Price per Strip</th>
              <th className="p-2">Quantity</th>
              <th className="p-2">Total Price</th>
            </tr>
          </thead>
          <tbody className="text-lg">
            {medicineCart &&
              // itemDetails?.items?.map((item, index) => (
              medicineCart.map((item, index) => (
                <tr key={index} className="border-b border-gray-200">
                  <td className="p-2">{`${item.name} (${item.measure})`}</td>
                  <td className="p-2">{`Tk. ${item.pricePerStrip}`}</td>
                  <td className="p-2">{item.stripCount}</td>
                  <td className="p-2">{`Tk. ${item.totalPrice}`}</td>
                </tr>
              ))}
          </tbody>
        </table>

        <table className="table w-full text-right border border-gray-300">
          <tbody>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Sub Total:</strong>
              </td>
              <td className="py-2">Tk. {checkoutDetails?.subtotal}</td>
            </tr>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Delivery Fee:</strong>
              </td>
              <td className="py-2">Tk. {checkoutDetails?.deliveryFee}</td>
            </tr>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Discount:</strong>
              </td>
              <td className="py-2">
                - Tk. {checkoutDetails?.discountedAmount}
              </td>
            </tr>
            <tr>
              <td className="w-40 text-left font-semibold py-2">
                <strong>Total:</strong>
              </td>
              <td className="py-2">Tk. {checkoutDetails?.total}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default InvoicePrint;
